// authInfo
const SET_AUTH_INFO = 'SET_AUTH_INFO';
// breadcrumb
const CHANGE_BREADCRUMB = 'CHANGE_BREADCRUMB';
const RESET_BREADCRUMB = 'SET_AUTH_INFO';
//
const CHANGE_COLLAPSED = 'CHANGE_COLLAPSED';
//
const CLEAR_STORE = 'CLEAR_STORE';

export {
  // authInfo
  SET_AUTH_INFO,
  // breadcrumb
  CHANGE_BREADCRUMB,
  RESET_BREADCRUMB,
  //
  CHANGE_COLLAPSED,
  //
  CLEAR_STORE
};
